httpServer {
  publicApiHttpPort = 8082
  privateApiHttpPort = 8087
}

kafka {

  TradesConsumer {
    topics = ["trades-topic"]
    offset = "latest"
    pollTimeout = "5s"
    threads = 1
    shutdownWait = "30s"

    driverProperties {
      "bootstrap.servers" = "localhost:9092,localhost:9094,localhost:9096"
      "group.id" = "data-processor-trades-group"
      "key.deserializer" = "org.apache.kafka.common.serialization.StringDeserializer"
      "enable.auto.commit" = false
      "auto.offset.reset" = "latest"
      "max.poll.records" = 500
      "fetch.min.bytes" = 1
      "fetch.max.wait.ms" = 10
    }
  }

  eventConsume {
    topics = ["filter-topic"]
    # при указанном group.id поле offset ниже не используется Kora — старт задаёт "auto.offset.reset"
    offset = "earliest"
    pollTimeout = "5s"
    threads = 1
    shutdownWait = "30s"

    driverProperties {
      "bootstrap.servers" = "localhost:9092,localhost:9094,localhost:9096"
      "group.id" = "data-processor-filter-events-group"
      "key.deserializer" = "org.apache.kafka.common.serialization.StringDeserializer"
      "enable.auto.commit" = false
      "auto.offset.reset" = "earliest"
      "max.poll.records" = 200
      "fetch.min.bytes" = 1
      "fetch.max.wait.ms" = 10
    }
  }
}

logging {
  levels {
    "ROOT" = "INFO"
    "ru" = "DEBUG"
    "org.apache.kafka" = "WARN"
  }
}

kafka.TradesConsumer.telemetry.logging.enabled = false
kafka.eventConsume.telemetry.logging.enabled = false