services:
  postgres:
    image: postgres:16-alpine
    container_name: alerting-postgres
    environment:
      POSTGRES_DB: filter_db
      POSTGRES_USER: filter
      POSTGRES_PASSWORD: filter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U filter -d filter_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - alyarma

  kafka:
    image: apache/kafka:3.9.1
    container_name: kafka
    ports:
      - "9092:19092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

      KAFKA_KRAFT_CLUSTER_ID: "DqqvGAQURkej_lZD0qN_vA"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824 # хранить данные до 1гб (или 24 часа, смотря что раньше наступит)
      KAFKA_LOG_SEGMENT_BYTES: 104857600 # такими сегментами хранить данные
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms256m"
      KAFKA_LOG4J_LOGGERS: "kafka.cluster=WARN,kafka.controller=WARN,state.change.logger=WARN"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - alyarma
    healthcheck:
      test: [ "CMD", "test", "-f", "/var/lib/kafka/data/meta.properties" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  kafka-init:
    image: apache/kafka:3.9.1
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./scripts/kafka-init.sh:/kafka-init.sh:ro
    entrypoint: [ "/bin/sh", "/kafka-init.sh" ]
    networks:
      - alyarma

  flink-jobmanager:
    image: flink:2.2.0-java21
    container_name: flink-jobmanager
    user: "0:0"
    command: jobmanager
    ports:
      - "8088:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.memory.process.size: 768m
        parallelism.default: 4
        state.checkpoints.dir: file:///opt/flink/checkpoints
        execution.checkpointing.interval: 10s
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - flink_checkpoints:/opt/flink/checkpoints
    networks:
      - alyarma
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8081/taskmanagers | grep -q '\"id\"'" ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  flink-taskmanager:
    image: flink:2.2.0-java21
    container_name: flink-taskmanager
    user: "0:0"
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.memory.process.size: 1024m
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 4
        state.checkpoints.dir: file:///opt/flink/checkpoints
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - flink_checkpoints:/opt/flink/checkpoints
    networks:
      - alyarma
    depends_on:
      flink-jobmanager:
        condition: service_started

  flink-data-processor-submit:
    image: flink:2.2.0-java21
    container_name: flink-data-processor-submit
    restart: "no"
    command:
      - bash
      - -c
      - flink run -d -m flink-jobmanager:8081 -c ru.flink.DataProcessorJob /opt/flink/usrlib/data-processor-job.jar
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    volumes:
      - ./artifacts/data-processor-job.jar:/opt/flink/usrlib/data-processor-job.jar:ro
    networks:
      - alyarma
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      flink-jobmanager:
        condition: service_healthy
      flink-taskmanager:
        condition: service_started

  filter-service:
    image: eclipse-temurin:25-jre-alpine
    container_name: alerting-filter-service
    command: [ "java", "-jar", "/app/filter-service.jar" ]
    ports:
      - "8081:8081"
      - "8086:8086"
    environment:
      KORA_CONFIG_APPLICATION: "application-docker.conf"
      DB_URL: "jdbc:postgresql://postgres:5432/filter_db"
      DB_USERNAME: "filter"
      DB_PASSWORD: "filter"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      JAVA_TOOL_OPTIONS: "-Xmx512m -Xms256m"
    volumes:
      - ./artifacts/filter-service.jar:/app/filter-service.jar:ro
    networks:
      - alyarma
    depends_on:
      postgres:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

  parser:
    image: eclipse-temurin:25-jre-alpine
    container_name: alerting-parser
    command: [ "java", "-jar", "/app/parser.jar" ]
    ports:
      - "9080:9080"
    environment:
      KORA_CONFIG_APPLICATION: "application.conf"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      JAVA_TOOL_OPTIONS: "-Xmx512m -Xms256m"
    volumes:
      - ./artifacts/parser.jar:/app/parser.jar:ro
    networks:
      - alyarma
    depends_on:
      kafka-init:
        condition: service_completed_successfully

  alert-service:
    image: eclipse-temurin:25-jre-alpine
    container_name: alerting-alert-service
    command: [ "java", "-jar", "/app/alert-service.jar" ]
    ports:
      - "8090:8090"
      - "7818:7818"
    environment:
      KORA_CONFIG_APPLICATION: "application-docker.conf"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      JAVA_TOOL_OPTIONS: "-Xmx512m -Xms256m"
    volumes:
      - ./artifacts/alert-service.jar:/app/alert-service.jar:ro
    networks:
      - alyarma
    depends_on:
      kafka-init:
        condition: service_completed_successfully



volumes:
  postgres_data:
  kafka_data:
  flink_checkpoints:

networks:
  alyarma:
    name: alyarma
    driver: bridge


# docker compose -f docker-compose.yml config
#  docker compose -f docker-compose.yml up -d
#  docker logs kafka-init
#  docker logs flink-data-processor-submit
