# Конфигурация для Docker-окружения

httpServer {
  publicApiHttpPort = 8090
}

alert {
  ws {
    port = 7818
  }
}

kafka {
    alertConsumer {
        topics = ["alert-topic"]
        offset = "latest"
        pollTimeout = "5s"
        threads = 1
        shutdownWait = "30s"

        driverProperties {
            "bootstrap.servers" = ${KAFKA_BOOTSTRAP_SERVERS}
            "group.id" = "alert-service-events-group"
            "key.deserializer" = "org.apache.kafka.common.serialization.StringDeserializer"
            "value.deserializer" = "org.apache.kafka.common.serialization.StringDeserializer"
            "enable.auto.commit" = false
            "fetch.max.wait.ms" = 10
            "log.level" = "WARN"
        }
    }
}

logging {
    levels {
        "ROOT" = "INFO"
        "ru" = "DEBUG"
        "org.apache.kafka" = "WARN"
    }
}

kafka.alertConsumer.telemetry.logging.enabled = false
