httpServer {
  publicApiHttpPort = 9080
  privateApiHttpPort = 8085
}
kafka {
  TradesProducer {

    topics = "trades-topic"
    driverProperties {
      bootstrap.servers = ${KAFKA_BOOTSTRAP_SERVERS}
      key.serializer = "org.apache.kafka.common.serialization.StringSerializer"
      value.serializer = "org.apache.kafka.common.serialization.ByteArraySerializer"
      max.block.ms = 1000
    }
  }
}
simulator {
  tickDelayMs = 100
  ticks = -1

  symbols = ["COIN1", "COIN2", "COIN3", "COIN4", "COIN5"]

  startPrices {
    BTC = 60000
    ETH = 3500
    SOL = 150
    XRP = 24
    ADA = 8
  }

  tickSizes = {}

  targetUsdVolumes {
    BTC = 100000.0
    ETH = 50000.0
    SOL = 10000.0
    XRP = 1000.0
    ADA = 1000.0
  }

  noiseTradersCount = 600
  momentumTradersCount = 600
  fundamentalTradersCount = 300
  marketMakersCount = 200
}
