httpServer {
  publicApiHttpPort = 9080
}
generator {
  startPrice = 50000000
  volumeBase = 1000
  volatility = 0.002
  trend = 0.00001
  spikeInterval = 100
  spikeAmplitude = 0.05
}
kafka {
  TradesProducer {
    topics = "trades-topic"
    driverProperties {
      bootstrap.servers = "localhost:9092"
    }
  }
}